version: "3"
services:
  casino_app:
    container_name: casino_container_v1
    image: casino_app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql_container_v1
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mpfrbb
      MYSQL_PORT: 3306
  mysql_container_v1:
    container_name: mysql_container_v1
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mysqluser
      MYSQL_ROOT_PASSWORD: mpfrbb
