version: "3"
services:
  casino_app:
    container_name: casino_container
    image: casino_app
    restart: always
    build: .
    ports:
      - 9090:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mpfrbb
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mysqluser
      MYSQL_ROOT_PASSWORD: mpfrbb
