version: "3"
services:
  server:
    image: casino_app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://127.0.0.1:3306/casino_db?useSSL=false
    networks:
      - casino_network
    depends_on:
      - mysql_container

  mysql_container:
    image: mysql:latest
    networks:
      - casino_network
    environment:
      - MYSQL_ROOT_PASSWORD=mpfrbb
      - MYSQL_DATABASE=casino_db
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mpfrbb

networks:
  casino_network: